- timestamp: '2025-12-21T20:54:26.982254'
  type: Task
  data:
    id: 1000
    owner: jose
    title: estante
    description: buscar estantes en mercado libre
    priority: LOW
    created_at: 2025-12-21 20:54:26.982254
    uri: jose_1000.txt
    status: IN PROGRESS
    comment: null
    finished_at: null
